name: A workflow for my Hello World file
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to welcome'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: greet with name
        uses: ./action-a
        with:
          MY_NAME: ${{ github.event.inputs.name }}
      - name: greet with name and location
        uses: ./action-a
        with:
          MY_NAME: ${{ github.event.inputs.name }}" from "${{ github.event.inputs.home }}
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: print hostname
        run: sh -c "echo cat /etc/hostname"
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v1
    - name: deploying app
      uses: ./action-a
      with:
        MY_NAME: ${{ github.event.inputs.name }}" - deploying now"
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: print hostname
      run: sh -c "echo cat /etc/hostname"